name: CI

on: [push, pull_request]

jobs:
    CI:
        name: Lint and Tests on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
        steps:
            - uses: actions/checkout@v3
            - name: install dependencies
              run: npm ci
            - name: run linter
              run: npm run lint
            - name: run tests
              run: npm test -w rmui-bigcomponents
